config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get '/login', to: "sessions#new"
  delete '/logout', to: "sessions#destroy"
  post '/login', to: "sessions#create"
  get '/signup', to: "users#new", as: :sign_up

  resources :users, only: [:create, :show, :destroy]
  resources :letters, only: [:new, :create, :show] do
    resources :shared_letters, only: [:create]
  end

  get '/templates/:id/random', to: "random_templates#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :templates

  def self.with_templates
    joins(:templates).group("categories.id")
  end
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  has_many :shared_letters
  has_many :users, through: :shared_letters
  validates_presence_of :content
end

app/models/shared_letter.rb
class SharedLetter < ApplicationRecord
  belongs_to :user
  belongs_to :letter
end

app/models/template.rb
class Template < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :letters, inverse_of: :owner, foreign_key: :owner_id
  has_many :shared_letters
  has_many :letters_shared_with_me, through: :shared_letters, source: :letter
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
  validates_confirmation_of :password, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def require_login
    unless session[:user_id]
      flash[:error] = "You must be signed in to view that page"
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user
      @letters = current_user.letters
      @shared_letters = current_user.letters_shared_with_me
    end
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :require_login, only: [:new, :show, :create]

  def new
    @letter = Letter.new
  end

  def show
    @letter = current_user.letters.find_by(id: id) ||
      current_user.letters_shared_with_me.find(id)
  end

  def create
    @letter = current_user.letters.build(letter_params)
    if @letter.save
      redirect_to letter_path(@letter)
    else
      flash[:error] = "Your letter must have content."
      render :new
    end
  end

  private

  def letter_params
    params.require(:letter).permit(:title, :content)
  end

  def id
    params[:id]
  end
end

app/controllers/random_templates_controller.rb
class RandomTemplatesController < ApplicationController
  def show
    category = Category.find(params[:id])
    template = category.templates.sample
    render json: template
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      flash[:notice] = "Start Writing!"
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

  private
  def email
    params[:email]
  end

  def password
    params[:password]
  end
end

app/controllers/shared_letters_controller.rb
class SharedLettersController < ApplicationController
  def create
    user = User.find_by(email: params[:recipients])
    letter = Letter.find(params[:letter_id])
    if user
      SharedLetter.create(letter: letter, user: user)
      flash[:success] = "You shared #{letter.title} with #{user.email}"
      redirect_to letter_path(letter)
    else
      flash[:error] = "This user doesn't exist."
      redirect_to letter_path(letter)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid account information"
      render :new
    end
  end

  def show
  end

  def destroy
    current_user.destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
- if current_user

  %h3 My Letters

  %div
    - @letters.each do |letter|
      %div
        = link_to letter.title, letter_path(letter)

  %h3 Letters Shared With Me

  %div
    - @shared_letters.each do |letter|
      %div
        = link_to letter.title, letter_path(letter)

  %div
    %h4
      = link_to "Write A New Letter", new_letter_path
- else

  %h1
    Welcome to Yours Truly.
    = link_to "Sign up", sign_up_path
    for an account!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title YoursTruly
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-default
      %div.container-fluid
        %a.navbar-brand(href=root_path)Yours Truly
        .nav.navbar-nav.navbar-right#nav-padding
          - if current_user
            %span
              Welcome, #{current_user.name}
            %span
              = link_to "Logout", logout_path, method: :delete
          - else
            %span
              = link_to "Login", login_path
    .flash
      - if flash[:error]
        .error
          = flash[:error]
      - if flash[:success]
        .success
          = flash[:success]
    %div.container
      = yield

app/views/letters/new.html.haml
%h1 Write Your Letter
= form_for @letter, html: {class: "form-horizontal"} do |f|
  %div.form-group
    %div.col-lg-10
      %label(for="template_category") Category
      = collection_select(:template, :category, Category.with_templates, :id, :name, prompt: "Select Template", class: "form-control", id: "select")
  %div.form-group
    %p
      = f.label :title, class: "col-lg-2, control-label"
    %div.col-lg-7
      = f.text_field :title, class: "form-control"
  %div.form-group
    %p
      = f.label :content, class: "col-lg-2, control-label"
    %div.col-lg-7
      = f.text_area :content, class: "form-control", rows: "15"

  %fieldset
    = f.submit "Yours Truly, #{current_user.name}", class: "btn, btn-primary"

app/views/letters/show.html.haml
%h1= "#{@letter.title}"
%div.well.well-lg
  = "#{@letter.content}"
= form_tag(letter_shared_letters_path(@letter), class: "form-horizontal") do
  %div.form-group
    %div.col-lg-10
      = label_tag :recipients, "Share This Letter"
      = text_field_tag :recipients
      = submit_tag "Share"

app/views/users/new.html.haml
%h1 Sign up for Yours Truly

= form_for @user do |f|
  %div
    = f.label :name
    = f.text_field :name
  %div
    = f.label :email
    = f.text_field :email
  %div
    = f.label :password
    = f.password_field :password
  %div
    = f.label :password_confirmation
    = f.password_field :password_confirmation

  %fieldset
    = f.submit "Create Account"

app/views/users/show.html.haml
%h1User Settings

= link_to "Delete Account", user_path(current_user), method: :delete